# torch.tensor

In [ ]:
import torch
import numpy as np

In [ ]:
t = torch.tensor(np.array([[1, 2, 3], [5, 6, 1]]))
t

tensor([[1, 2, 3],
        [5, 6, 1]], dtype=torch.int32)

In [ ]:
t.repeat(1, 3)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [5, 6, 1, 5, 6, 1, 5, 6, 1]], dtype=torch.int32)

In [ ]:
t.repeat(2, 1)

tensor([[1, 2, 3],
        [5, 6, 1],
        [1, 2, 3],
        [5, 6, 1]], dtype=torch.int32)

In [ ]:
t.repeat(2, 2)

tensor([[1, 2, 3, 1, 2, 3],
        [5, 6, 1, 5, 6, 1],
        [1, 2, 3, 1, 2, 3],
        [5, 6, 1, 5, 6, 1]], dtype=torch.int32)

텐서 반복해서 채우기

In [ ]:
t.repeat(1, 3, 3, 1)

tensor([[[[1, 2, 3],
          [5, 6, 1],
          [1, 2, 3],
          [5, 6, 1],
          [1, 2, 3],
          [5, 6, 1]],

         [[1, 2, 3],
          [5, 6, 1],
          [1, 2, 3],
          [5, 6, 1],
          [1, 2, 3],
          [5, 6, 1]],

         [[1, 2, 3],
          [5, 6, 1],
          [1, 2, 3],
          [5, 6, 1],
          [1, 2, 3],
          [5, 6, 1]]]], dtype=torch.int32)

# 텐서 펼치기(flatten)

In [ ]:
t = torch.tensor(np.array([[1, 2, 3],[4, 5, 6]]))
t2 = torch.tensor(np.ones((2,3,3,4)))

In [ ]:
print(f"original dimension: {t.shape}")
print(f"dim after flatten: {t.flatten().shape}")

original dimension: torch.Size([2, 3])
dim after flatten: torch.Size([6])


start_dim 인자를 통해 flatten을 시작할 차원을 정해줄 수 있다.

In [ ]:
print(f"original dimension: {t2.shape}")
print(f"dim after flatten: {t2.flatten(start_dim=2).shape}")

original dimension: torch.Size([2, 3, 3, 4])
dim after flatten: torch.Size([2, 3, 12])


# 차원 위치 바꾸기 (permute)
텐서의 위치를 바꾼다.(transpose)

In [ ]:
t3 = torch.tensor(np.ones((2, 3, 4, 5)))

In [ ]:
print(f"original dimension: {t3.shape}")
print(f"dim after flatten: {t3.permute(2, 0, 3, 1).shape}")

original dimension: torch.Size([2, 3, 4, 5])
dim after flatten: torch.Size([4, 2, 5, 3])


# 최대값을 갖는 인덱스 찾기(torch.argmax)
최대 값을 갖는 위치의 인덱스를 반환한다.
dim인자를 통해 기준 차원을 정해줄 수 있다.

In [ ]:
t = torch.tensor(np.array([[1, 2, 3, 4, 5], [3, 4, 2, 3, 5], [4, 2, 15, 2, 1]]))
t

tensor([[ 1,  2,  3,  4,  5],
        [ 3,  4,  2,  3,  5],
        [ 4,  2, 15,  2,  1]], dtype=torch.int32)

In [ ]:
t.argmax()

tensor(12)

In [ ]:
t.argmax(dim=0)

tensor([2, 1, 2, 0, 0])

In [ ]:
t.argmax(dim=1)

tensor([4, 4, 2])

# 불리언의 모든 값이 참인지 or 하나라도 참인지 확인 하기 (.all() .any())

In [ ]:
t = torch.tensor(np.ones((2, 3)))
t = t == True
t

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
t.all()

tensor(True)

In [ ]:
t.any()

tensor(True)

In [ ]:
t = torch.tensor(np.ones((2, 3)))
t[0, 2] = 0
t = t == True
t

tensor([[ True,  True, False],
        [ True,  True,  True]])

In [ ]:
t.all()

tensor(False)

In [ ]:
t.any()

tensor(True)